config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'comments/create'

  get 'comments/destroy'

  get 'loves/read'

  get 'loves/index'

  resource :love, only: [:index]

  resources :notifications, only: [:create]

  resources :posts do
    member do
      get 'like'
      get 'love'
    end
    resources :comments, only: [:create, :destroy]
  end

  resources :comments, only: [:create, :destroy] do
    member do
      get 'like'
      get 'love'
    end
  end

   root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  acts_as_votable
  has_many :loves, as: :adorable

  validates :body, presence: true
end

app/models/love.rb
class Love < ActiveRecord::Base
  belongs_to :adorable, polymorphic: true
  belongs_to :user
  belongs_to :receiver, class_name: 'User', foreign_key: 'receiver_id'

  before_validation do
    set_receiver
  end

  scope :checked, -> { where(is_checked: true) }
  scope :unchecked, -> { where(is_checked: false) }

  def set_receiver
    if adorable
      case adorable_type
      when 'Post'
        self.receiver = adorable.user
      when 'Comment'
        self.receiver = adorable.user
      else
        raise 'not supported adorable_type'
      end
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :user
	has_many :loves, as: :adorable
	has_many :comments, dependent: :destroy
	acts_as_votable


	def init
		self.like_number ||=0.0
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  acts_as_voter

  has_many :comments
  has_many :posts
  has_many :loves
  has_many :loved_loves, class_name: 'Love', foreign_key: 'receiver_id'

  def self.find_for_facebook_oauth(auth)
    user = where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.oauth_token = auth.credentials.token
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
    
    logger.info "Aaaaaaa"
    logger.info user.email
    logger.info auth.info.inspect
    logger.info auth.inspect
    user
  
    # 이 때는 이상하게도 after_create 콜백이 호출되지 않아서 아래와 같은 조치를 했다.
    
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
  
  def facebook
    @facebook ||= Koala::Facebook::API.new(oauth_token)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :update, :like, :love]
  before_action :set_post, except: [:like, :love]
  before_action :set_comment, only: [:destroy, :like, :love]

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    @comment.like_number=0
    @comment.save
  end

  def like
    if current_user.voted_up_on? @comment
      @comment.downvote_from current_user
    else
      @comment.liked_by current_user
    end
  end

  def love
    Love.create!(adorable: @comment,user: current_user)
  end
  def destroy
    @comment.destroy
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/loves_controller.rb
class LovesController < ApplicationController
  before_action :authenticate_user!
  # before_action :set_love, only: [:read]

  def unchecked
    @loves = current_user.loves.unchecked
  end

  def index
    @loves = current_user.loved_loves
    # render text: @s.pluck(:adorable_id,:adorable_type, :user_id)


  end

  def read
    @loves = current_user.loved_loves.last
                 # .where("created_at >= ?",20.seconds.ago)
    # if(@loves.count != 0)
    render :json => @loves.to_json(:include => :user)
    # else
    #   render :json => @loves.to_json(:include => :user)
    # end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  # def set_love
  #   @love = Love.find(params[:id])
  # end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :update, :like, :love]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like, :love]


  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order(:cached_votes_up => :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  def love
    Love.create!(adorable: @post,user: current_user)
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      @post.like_number=0
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def like
    if current_user.voted_up_on? @post
      @post.downvote_from current_user
    else
      @post.liked_by current_user
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/loves_helper.rb
module LovesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<li id="comment_<%=comment.id %>">
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <section class="comment-list">
        <!-- First Comment -->
        <article class="row">
          <div class="col-md-10 col-sm-10">
            <div class="panel panel-default arrow left">
                <% if current_user == comment.user %>
              <div class="panel-body comment_selected">
                <% else %>
                <div class="panel-body">
                <% end %>

                    <div class="comment-post">

                  <p>
                    <%= comment.body %>
                  </p>
                </div>
                <div class="text-right">
                  <time class="comment-date">Created <i class="fa fa-clock-o"><%= time_ago_in_words(comment.created_at) %></i> ago</time>

                  <% if user_signed_in? %>
                  <p id="like-comment-<%= comment.id %>">

                    <% if current_user != comment.user %>
                    <%= link_to "love",love_comment_path(comment),remote:true, data:{confirm:"Are you sure?"} %> |
                    <% end %>

                    <% if current_user.voted_up_on? comment %>
                        <%= link_to "liked",like_comment_path(comment), remote: true %>
                    <% else %>
                        <%= link_to "like",like_comment_path(comment), remote: true %>
                    <% end %>

                    <b><%= comment.get_likes.size %></b>
                  </p>
                  <% else %>
                      <p>like <%= comment.get_likes.size %>
                      </p>
                  <% end %>


              </div>
                <% if user_signed_in? %>
                    <% if current_user == comment.user %>
                        <div class="text-right">
                          <%= link_to "", [comment.post, comment], class:'btn btn-default glyphicon glyphicon-remove', method: :delete, remote: true, data: { confirm: "Are you sure?" } %>
                        </div>
                    <% end %>
                <% end %>
                <!--<p class="text-right"><a href="#" class="btn btn-default btn-sm"><i class="fa fa-reply"></i> reply</a></p>-->
              </div>
            </div>
          </div>
        </article>
      </section>
    </div>
  </div>
</div>
</li>

app/views/comments/_comments.html.erb
<div class="comments">
  <div class="comments_list">
    <%= render "comments/list" %>
  </div>
  <div class='comments_form'>
    <%= render "comments/form" %>
  </div>
</div>

app/views/comments/_form.html.erb
<% comment = @post.comments.new %>
<div id="comments_form_<%=@post.id%>">
<%= simple_form_for([@post, comment], remote: true ) do | f | %>


      <% if user_signed_in? %>

          <div class='form-inputs'>
            <%= f.input :body, label: false, placeholder: 'Add a comment.',  input_html: { rows: 5 } %>
          </div>


  <div class='form-actions'>
    <%= f.button :submit %>
  </div>
      <% end %>
<% end %>
</div>

app/views/comments/_list.html.erb
<ul id="comments_list_<%=@post.id%>">
<% if @post.comments.size > 0 %>
  <%= render @post.comments %>
<% else %>
  <li>
    ** 적극적으로 커맨트로 어필하세요!!
  </li>
<% end %>
</ul>

app/views/comments/create.js.erb
<% if @comment.errors.size == 0 %>
  $('<%=j render @comment %>').appendTo($("#comments_list_<%=@post.id %>")).hide().fadeIn('fast');
  $("#comments_form_<%=@post.id %> form")[0].reset();
<% else %>
  alert("Please submit after commenting...");
<% end %>

app/views/comments/destroy.js.erb
$("#comment_<%=@comment.id %>").slideUp('fast');

app/views/comments/like.js.erb
if ($("#like-comment-<%=@comment.id %> a").text() == "liked"){
  $("#like-comment-<%=@comment.id %> a").text("like")

}
else{
  $("#like-comment-<%=@comment.id %> a").text("liked")
}

$("#like-comment-<%=@comment.id %> b").text("<%=@comment.get_likes.size%>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phildate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />

</head>
<body>
<!-- Fixed navbar -->

<nav class="navbar navbar-inverse navbar-fixed-top">

  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="../"><b>PHIL</b><i>DATE</i><3</a>

      <ul class="nav navbar-nav navbar-right">
        <!--<li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>-->





          <% if user_signed_in? %>
            <li id="who">
              <%= link_to "요셉&성수", loves_index_path, :class=>"wholovesyou"%>
            </li>
            <li id="love">
              <button type="button" class="btn btn-default-1">
                <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
              </button>
            </li>
            <li id="you">
              <%= link_to "YOU", root_path, :class=>"helloworld"%>
            </li>
            <!--<li><%= link_to "로그아웃 :)", destroy_user_session_path, method: :delete, data: {confirm: "Are you sure?" }%> </li>-->
          <% else %>
            <li><%= link_to " 페이스북으로 로그인 :)", user_omniauth_authorize_path(:facebook)%> </li>
          <% end %>
      </ul>
    </div>
  </div>
</nav>

    <div class="container">
      <div class="text-center loves">
        <ul>
          this is other words
        </ul>

      </div>
      <%= yield %>

    </div> <!-- /container -->
</body>
</html>

<script>

  function animateHeart(){
    $('.wholovesyou').css({paddingleft:0
    });
    $('.wholovesyou').animate({paddingRight:'20px'},5000,function(){
      animateHeart();
    })
  }
  var originname="요셉&성수";
  $(".btn-default-1").click(function(){
    $(location).attr("href", "../loves/index");
  });

  function getData(){
    $.ajax({
      url: "/loves/read",
      dataType: "json",
      data: {
        prezzario: "enjoy"
      },
      success: function (data) {
        animateHeart();
        return $('.wholovesyou').text(data.user.name)

        }

      });
    }

  getData()
  var myVar = setInterval(getData, 10000);


</script>

app/views/loves/index.html.erb
<div class="list-group">

  <% @loves.each do |love| %>
    <% if (love.adorable_type == 'Post') %>

      <a href="../posts/<%=love.adorable.id%>" class="list-group-item">
        <h4 class="list-group-item-heading"><%=love.user.name%> wants you</h4>
        <p class="list-group-item-text"><%= "Post Title: " + love.adorable.title%></p>

      </a>

      <% else %>

          <a href="../posts/<%=love.adorable.post_id%>" class="list-group-item">
            <h4 class="list-group-item-heading"><%=love.user.name%> wants you</h4>
            <p class="list-group-item-text"><%"Comment: "+love.adorable.body %></p>

          </a>
          <% end %>


<% end %>
  <a href="../WHO" class="list-group-item">
    <h4 class="list-group-item-heading">성수와 & 요셉이가 그대 <%= current_user.name %>씨를 사랑합니다. </h4>
  </a>
</div>

app/views/loves/read.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>


<% if user_signed_in? %>
    <% if current_user == @post.user %>
        <div class="text-right">
          <%= link_to 'Edit', edit_post_path(@post) %> |
          <%= link_to 'Back', posts_path %>
        </div>
    <% end %>
<% end %>


<%= render "comments/comments" %>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content , :input_html => {:rows => 10 ,:size => 30} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>



<script>


  $("#post_content").height($(window).height()-350);
// this is for phone user interface

  $("#post_title").click(function(){
   $("#post_content").css({
     top:300
   })
  })

  $("#post_content").click(function(){
    if($(window).height()<350) {
      $("#post_content").css({top: 300});
      $("#post_content").height($(window).height());
      $("#post_content").animate({top: 0}, 500);
    }
  });


  $(window).resize(function(){
    if($(window).height() > 350) {
      $("#post_content").height($(window).height() - 350);
    }
  });
</script>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>


<div class="text-center">
  <% if user_signed_in? %>
      <%= image_tag(current_user.image, size: '50x50', style:'border-radius:3px;vertical-align:top;') if current_user.image %>
  <% end %>
  <h2 class="intro">PHILDATE</h2>
  <p class="des">외모와 스펙으로 사랑을 평가하고 호감이 가는 이시대 <br><b>"지 루 해!" "역 겨 워!"</b></br> 혁신적인 방법으로 스펙 외모 그 외에 모든것으로 부터 자유로운 사랑을 경험하세요!
  <br>오로지 자신의 생각과 철학으로 어필하고 사랑이 이루어지는 PhilDate(Philosophy Date)<br>
  당신의 순결한 그리고 고결한 철학관으로 진정성 있는 만남을 가져가세요!</p>
  <% if user_signed_in? %>
     <%= link_to "글작성", new_post_path, class:'btn btn-default glyphicon glyphicon-pencil' %>
  <% end %>
</div>





<div class="container">
  <h3>그대의 이야기 철학 그리고 사랑</h3>
  <h4><b>오늘의 주제:</b> "당신의 이상적인 배우자 상은 어떻게 되요? 자신의 경험과 철학을 바탕으로 한 진실한 배우자상 이야기 해주세요!"</h4>

  <div class="list-group">

    <% @posts.each do |post| %>

        <a href="posts/<%= post.id %> " class="list-group-item">
          <h4 class="list-group-item-heading"><%=post.title %></h4>
          <p class="list-group-item-text"><%= (post.content.size>80) ? post.content.first(80)+"..." : post.content %></p>
        </a>
        <div class="text-right">
          <p id="like-post-<%= post.id %>">
        <% if user_signed_in? %>
                <% if current_user != post.user %>
                  <%= link_to "love",love_post_path(post),remote:true, data:{confirm:"Are you sure?"} %> |
                <% end %>
          <% if current_user.voted_up_on? post %>

              <%= link_to "liked",like_post_path(post), remote: true %>
          <% else %>
            <%= link_to "like",like_post_path(post), remote: true %>
          <% end %>


        <% else %>
            like
        <% end %>
          <b><%= post.get_likes.size %></b>
          </p>
        </div>

    <% end %>
  </div>
</div>

app/views/posts/like.js.erb
if ($("#like-post-<%=@post.id %> a").text() == "liked"){
  $("#like-post-<%=@post.id %> a").text("like")

}
else{
  $("#like-post-<%=@post.id %> a").text("liked")
}

$("#like-post-<%=@post.id %> b").text("<%=@post.get_likes.size%>")

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<h1 class="header">
  <%= @post.title %>
</h1>

<h4 class="post_show">
  &nbsp;&nbsp;&nbsp;&nbsp;<%= @post.content %>
</h4>
</div>

<% if user_signed_in? %>
    <% if current_user == @post.user %>
        <div class="text-right">
          <%= link_to 'Edit', edit_post_path(@post) %> |
          <%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' }%> |
          <%= link_to 'Back', posts_path %>
        </div>
    <% end %>
<% end %>


<%= render "comments/comments" %>

app/views/welcome/index.html.erb
<h2>PHILDATE</h2>
<p>외모와 스펙으로 사랑을 평가하고 호감이 가는 이시대 <br><b>"지 루 해!" "역 겨 워!"</b></br> 혁신적인 방법으로 스펙 외모 그 외에 모든것으로 부터 자유로운 사랑을 경험하세요!
  <br>오로지 자신의 생각과 철학으로 어필하고 사랑이 이루어지는 PhilDate(Philosophy Date)<br>
  당신의 순결한 그리고 고결한 철학관으로 진정성 있는 만남을 가져가세요!</p>

<br />
<%= link_to "글작성", posts_path, class:'btn btn-default' %>

<%= link_to 'New Post', new_post_path %>